### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Jesus-Suarez** [kshetline/ligatures-limited#3] opened 2020-05-24 16:48 UTC
- Issue Type: `Performance`
- Extension Name: `ligatures-limited`
- Extension Version: `1.0.1`
- OS Version: `Linux x64 4.15.0-30deepin-generic`
- VSCode version: `1.45.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/jesus/kshetline.ligatures-limited-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kshetline** [comment] 2020-05-24 18:30
Can you provide more specific info? I've not personally run into this problem myself. The code has been written to break up its formatting operations into asynchronous chunks, if necessary, to avoid hogging the CPU for too long at any one given time.

**Comment by kshetline** [comment] 2020-05-24 18:31
It looks like the file you intended to attach, /home/jesus/kshetline.ligatures-limited-unresponsive.cpuprofile.txt, was not attached.

**Comment by kshetline** [comment] 2020-05-29 14:00
As there has been no follow-up for five days, and I can neither reproduce this problem nor do I have other reports of this problem, I'm closing this issue. Please feel free to post the issue again if necessary.

**Closed** 2020-06-01 18:20 UTC
